review for G-sgd
vitalab/vitalab.github.io pull request #507
Opened 2020-09-24 18:34 UTC by MarcoArmenta

2020-10-02 17:23 UTC, jodoin reviewed
There are rendering error.  Please correct it.

2020-10-15 18:25 UTC, lemairecarl requested changes
Please fix the rendering errors.

2020-10-15 18:25 UTC, lemairecarl commented on article/_posts/2020-09-23-G-SGD.md
> +A path is represented by a vector $$p=(p_1,...,p_m)^T$$ and if edge e is contained in path p, then $$p_e$=1$ and otherwise $$p_e=0$$. These vectors have L entries that are non-zero. The value of path
Rendering error, probably because of `$$p_e$=1$`

2020-10-15 18:25 UTC, lemairecarl commented on article/_posts/2020-09-23-G-SGD.md
> +* They consider the set of path vectors $$\mathcal{P} \subser \{ 0,1 \}^m$$.
rendering error

2020-10-15 18:25 UTC, lemairecarl commented on article/_posts/2020-09-23-G-SGD.md
> +# $$\mathcal{G}-SGD optimization algorithm$$
Please put "optimization algorithm" outside the math block

2020-10-15 20:12 UTC, MarcoArmenta commented
How can I see where are the rendering errors? Besides clicking "view file" in the commit, because that does not let me see if there are errors.

2020-10-15 21:07 UTC, lemairecarl commented
You will need to preview your post locally, see https://vitalab.github.io/howto/

2020-10-23 18:44 UTC, AntoineTheb approved these changes
Minor comments, haven't verified the equations

2020-10-23 18:44 UTC, AntoineTheb commented on article/_posts/2020-09-23-G-SGD.md
> +A path is represented by a vector $$p=(p_1,...,p_m)^T$$ and if edge e is contained in path p, then $$p_e=1$$ and otherwise $$p_e=0$$. These vectors have L entries that are non-zero. The value of path
edge $$e$$ and path $$p$$ [...] $$L$$ entries

2020-10-30 16:43 UTC, MarcoArmenta commented on article/_posts/2020-09-23-G-SGD.md
> +A path is represented by a vector $$p=(p_1,...,p_m)^T$$ and if edge e is contained in path p, then $$p_e=1$$ and otherwise $$p_e=0$$. These vectors have L entries that are non-zero. The value of path
Done!

2020-12-22 14:00 UTC, merged